### ISSUE TITLE
unit test my own udf?

### ISSUE THREAD

**Issue by csimplestring** [aerospike/aerospike-lua-core#2]
Hi, I am now developing UDF in aerospike, which is useful. 
But I have a question: how to unit test my own udf?

Currently, I have to register udf on server manually and call user-defined function through 'ascli apply-record-udf ' command. 

Is there any better solution for udf unit testing?

**Comment by maverickgautam** [comment]
I have made a aerospike-unit module, which one can use while writing unit, Integration test cases . (Java Project)

Open Source CodeBase:
https://github.com/maverickgautam/Aerospike-uni

Readme available at
https://github.com/maverickgautam/Aerospike-unit/blob/master/README
It is a Java Wrapper over the actual Aerospike . 
Hope Aerospike community finds this useful .

Lua Test Cases are supported.
