### ISSUE TITLE
The numRead variable is being incremented no matter if the filter returned an object or nil

### ISSUE THREAD

**Issue by ttrifonov** [aerospike/aerospike-lua-core#7]
There is a bug in lstack.filter() when a filter is being applied. The numRead variable is being incremented no matter if the filter returned an object or nil. Thus when trying to read first 100 values matching a filter predicate - only the first 100 items in the stack are scanned. Expected - the stack to be continuosly scanned until 100 values matching the filter predicate are found.

Currently the documentation for LSTACK says:

`Find the first n values satisfying the predicate p.`

while the current behaviour of the code is:

`Find those values amongst the first n values in the stack that satisfy the predicate p.`

Note: I've created a pull request with the affected code.

**Comment by ttrifonov** [comment]
It is more than a month this is been reported, and even no comment from Aerospike? Is this a bug or feature? If it is a bug - this is a severe bug, or maybe you think that too few people are using LSTACK so it doesn't worth fixing it?

**Comment by wchu-citrusleaf** [comment]
Apologies for the delay. Thanks for the heads up. We did review it internally, and have merged in the request.
